### PR TITLE
add pkg-config along with FindCapsImage and make dirent a submodule

### PR DESCRIPTION
**Pull request by jopadan**

### CODE REVIEW

**Comment by simonowen** [comment]
Looks good overall, but I feel switching to a sub-module for a single header is too heavy and complicates repo cloning. If you feel it's really worth the update flexibility I'd prefer FetchContent to grab it during the project configuration phase instead.

**Comment by jopadan** [comment]
Trying the following code
```c
include(FetchContent)
FetchContent_Declare(
     dirent
     GIT_REPOSITORY http://github.com/tronkko/dirent
     GIT_TAG master
     FIND_PACKAGE_ARGS
)
FetchContent_MakeAvailable(dirent)
```
fails with 
```c
-- Using '5' suffix on include directory
[ 11%] Creating directories for 'dirent-populate'
[ 22%] Performing download step (git clone) for 'dirent-populate'
Cloning into 'dirent-src'...
fatal: unable to access 'http://github.com/tronkko/dirent/': Problem with the SSL CA cert (path? access rights?)
Cloning into 'dirent-src'...
fatal: unable to access 'http://github.com/tronkko/dirent/': Problem with the SSL CA cert (path? access rights?)
Cloning into 'dirent-src'...
fatal: unable to access 'http://github.com/tronkko/dirent/': Problem with the SSL CA cert (path? access rights?)
-- Had to git clone more than once:
          3 times.
CMake Error at dirent-subbuild/dirent-populate-prefix/tmp/dirent-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'http://github.com/tronkko/dirent'

```
and populates only _deps/dirent-subbuild

**Comment by simonowen** [comment]
I think the error is that you're missing the `s` from your `https` protocol? Best to pin to a specific hash instead of a branch too, since the branch changes as more is committed to it.  If the `dirent.h` in the repo is ready to use you can just populate the contents and set the include directory to point at it.

Something like this might do the trick:

```CMake
FetchContent_Declare(
  dirent
  GIT_REPOSITORY https://github.com/tronkko/dirent.git
  GIT_TAG 328e7fca1497f1d990d8b55b3cec39c869e3a6a8)
FetchContent_Populate(dirent)
target_include_directories(${PROJECT_NAME} PRIVATE ${dirent_SOURCE_DIR}/include)
```

**Comment by jopadan** [comment]
the problem seems to be solved by setting `git config --global http.sslverify "false"` and was local host related.
FIND_PACKAGE_ARGS seems to cause similar trouble.
After squashing the commits it successfully installs with the following commands
`cmake --install-prefix=/use . -DADD_INCLUDE_SUFFIX=ON -DWIN32=ON && make install`

**Pull request closed without merging**
